### ISSUE TITLE
Combine App and User Claims

### ISSUE THREAD

**Issue by ponsakthi** [AzureADSamples/WebAPI-OnBehalfOf-DotNet#3]
Is there a way to generate Azure Application Claims and User Claims in a single Access token? Is there any example available?

**Comment by dstrockis** [comment]
Hey @ponsakthi - Can you give a little more detail of what you're looking for? The tokens you get in this sample should have both information about the user and the appId of the calling application... Is there something more you need?

**Comment by ponsakthi** [comment]
I am trying to create a access token from a .Net Windows Application.
This is the code I tried to use.
`var userToken = authenticationContext.AcquireToken(_resourceId, _AppId, new Uri(_postLogoutRedirectUrl), PromptBehavior.Always);
string authority = String.Format(CultureInfo.InvariantCulture, "https://login.microsoftonline.com/{0}", _AzureActiveDirectoryTenant);
 AuthenticationContext authContext = new AuthenticationContext(authority);
var token = authContext.AcquireToken(_resourceId, _clientCredential, new UserAssertion(userToken));`

And I get the error , " Error validating credentials. AADSTS50013: Assertion audience claim does not match the required value."

Any idea why is this?

**Comment by dstrockis** [comment]
This is the "OnBehalfOf" flow, where a middle tier service/API redeems the access token it receives for another access token to a downstream service/API.  So in the above code, the `_resourceId` in the first call must be the *AppId URI* of the app that's asking for a token (indicated by the clientId you used).

Just to check - are you sure you need to perform this OnBehalfOf flow?  If all you need to do is get a token in your app, there are simpler samples in this github org that show how.

**Comment by ponsakthi** [comment]
I changed the _resourceId to AppId URI and it worked. Thanks
To answer your question : I don't want to perform OnbehalfOfFlow, but I need my app to generate a token that has both user and app claims.

**Comment by ponsakthi** [comment]
Hey @dstrockis . Should the requesting app(1st call) have delegated permissions to the destination app(App in 2nd call)?
