### ISSUE TITLE
Fix lookup within token store

### ISSUE THREAD

**Issue by lindydonna** [AzureADSamples/WebAPI-OnBehalfOf-DotNet#4]
Fix line [TodoListController.cs#L135](https://github.com/AzureADSamples/WebAPI-OnBehalfOf-DotNet/blob/94af76a01369d6ddf6b871c8e21da9147490701a/TodoListService/Controllers/TodoListController.cs#L135) to pass username to UserAssertion constructor as a hint to ADAL for cache lookup.

**Comment by dstrockis** [comment]
Probably need to do a custom cache instead/as well.

**Comment by dstrockis** [comment]
^That's a note to self :)

**Comment by dstrockis** [comment]
Fixed https://github.com/AzureADSamples/WebAPI-OnBehalfOf-DotNet/commit/5eb2f042fd29022174dce340d50bf373d422a82e
